### PR TITLE
Fix star display + pen color scheme

### PR DESCRIPTION
**Pull request by sachi-d**
The starting point of dots, the star display had an underlying "0" which altered the display of the star, which was removed from the array. The pen colors were updated to a kid-friendly color scheme.

### CODE REVIEW

**Comment by walterbender** [comment]
This is good work but there is one minor issue: the easel text in the circles is misaligned when the number is > 9, e.g. two digits. Can you adjust the position of the text depending upon the number of digits? Or better yet, center align?

**Comment by walterbender** [comment]
Could you please separate all of the formatting changes into a separate commit? It is hard to see where you addressed the label alignment because of all of he other changes.

**Comment by sachi-d** [comment]
The last 2 commits were squashed to https://github.com/sugarlabs/connect-the-dots-activity/pull/9/commits/41899a5a739d2ed498b95a770a603338dea66fc7, which contains the label fix.

**Comment by walterbender** [comment]
You changes seem to work. I am still confused by all the formatting changes you added to the PR. They really should be in a separate commit. But I will merge and we can address them separately.

**Pull request merged**
