### PR TITLE
 Numbers not in circles after 13 star button presses 

### LINKED ISSUE #16: Numbers not in circles after 13 star button presses
Activity showing unexpected behavior.
conn-un

Steps to reproduce:
1) Click the **Star** button 13 times.

### PR DESCRIPTION
**Pull request by DipanshKhandelwal**
Fixes #16 .

### CODE REVIEW

**Comment by quozl** [comment]
Reviewed.  I disagree with the change.  While it may fix the symptom for you, it does not seem right to me.

- [ ] the commit message is inadequate; it does not explain what the cause of the problem was,
- [ ] the constant `12` is not explained, and code a few lines later uses `shapes.length`, so is inconsistent,
- [ ] the conditional check a few lines later seems intended not to use shapes once they are exhausted.

@walterbender, please review and comment?

**Comment by DipanshKhandelwal** [comment]
@quozl thanks for the review.
1. Can you help me wiith the commit message please.
2. I have changed he number 12 with ```shapes.length ```. Thanks.
3. Should we use the random shapes once our shapes are exhausted?

**Comment by DipanshKhandelwal** [comment]
@quozl now after the fixed number of shapes it will now randomly generate the shapes.

**Comment by quozl** [comment]
Thanks for the update.  You wrote:

> Can you help me wiith the commit message please.

Sure.  See [making commits](https://developer.sugarlabs.org/contributing.md.html#making%20commits) in our [guide for developers](https://developer.sugarlabs.org).

When writing, consider your audience.  Your reviewers are developers who could fix the problem but don't have time to do so, or they would have done it already.  Reviewers want to ensure the issue is fixed, that code quality is increased, that no new regressions are added, and that the commit history (not the GitHub pull request) accurately reflects the change.  Audience is also future developers who are looking for cause of a regression, using cherry-pick or `git bisect`, so they want the commit message to be understandable.  Often they look at the [history of commits](https://github.com/sugarlabs/connect-the-dots-activity/commits/master) first, using GitHub or local git tools.

Putting it another way; it may not be enough simply to fix the problem, you may also have to communicate the thought process you went through to achieve it.

> after the fixed number of shapes it will now randomly generate the shapes.

The [overall change](https://github.com/sugarlabs/connect-the-dots-activity/pull/17/files) is much easier to understand now, thanks.

Previously, the first call to `new_position` did return.  Now, the first call to `new_position` does much more.  Did you intend that?  Why?

@walterbender, please review and comment?

**Comment by DipanshKhandelwal** [comment]
Thanks @quozl .
There is an unnecessary call to ```new_positions``` .

**Comment by quozl** [comment]
Ah, thanks.

**Comment by walterbender** [comment]
I think the root of the problem in this issue lies in the block of code beginning here:
https://github.com/DipanshKhandelwal/connect-the-dots-activity/blob/7bd9e7f9a4df3c9b3f74ae045e74d75379259d98/js/activity.js#L253

After we exhaust the pre-calculated shapes, random positions are assigned. But the dot positions and the number (label) positions are calculated independently. That would explain the misalignment.

**Comment by quozl** [comment]
@DipanshKhandelwal, while reviewing `new_positions` as at your d99096c, I saw some code common to each branch of the `if`, so moved it outside the `if`, and pushed to your branch as 9d8c74b.  Please consider it.

**Comment by DipanshKhandelwal** [comment]
@quozl Yes, there was too much of extra lines. Thanks :+1:

**Pull request merged**
